# Generated by Django 3.1.5 on 2022-04-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0003_auto_20220406_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=75)),
                ('eorganizers', models.CharField(max_length=50)),
                ('ediscription', models.TextField()),
                ('ecoordinators', models.TextField()),
            ],
        ),
    ]
